language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
