# TravisCI configuration for brain/hierarchy

language: php
os:
  - linux
dist: xenial

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - composer validate --strict

install:
  - composer update

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
